// FILE: QRScannerPairingValidator.swift
// Purpose: Classifies scanned QR payloads — supports both xatlas LAN QR and relay QR formats.
// Layer: View support

import Foundation

enum QRScannerPairingValidationResult {
    case success(CodexPairingQRPayload)
    case lanSuccess(XatlasLANPairingPayload)
    case scanError(String)
    case bridgeUpdateRequired(CodexBridgeUpdatePrompt)
}

private let qrScannerBridgeUpdateCommand = "npm install -g xatlas-bridge@latest"

func validatePairingQRCode(_ code: String, now: Date = Date()) -> QRScannerPairingValidationResult {
    guard let data = code.data(using: .utf8) else {
        return .scanError("QR code contains invalid text encoding.")
    }

    // Check for xatlas LAN QR first (from the desktop app's Settings → Remote Access)
    if XatlasDirectService.isLANQR(code), let lanPayload = XatlasDirectService.parseLANQR(code) {
        return .lanSuccess(lanPayload)
    }

    // Check for relay QR (from xatlas-bridge)
    let decoder = JSONDecoder()
    if let payload = try? decoder.decode(CodexPairingQRPayload.self, from: data) {
        guard payload.v == codexPairingQRVersion else {
            return .bridgeUpdateRequired(
                makeScannerBridgeUpdatePrompt(
                    message: "This QR code was generated by a different version. Update the bridge on your Mac."
                )
            )
        }

        guard !payload.relay.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("QR code is missing the relay URL. Re-generate the code from the bridge.")
        }

        guard !payload.sessionId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .scanError("QR code is missing the session ID. Re-generate the code from the bridge.")
        }

        let expiryDate = Date(timeIntervalSince1970: TimeInterval(payload.expiresAt) / 1000)
        guard expiryDate.addingTimeInterval(codexSecureClockSkewToleranceSeconds) >= now else {
            return .scanError("This pairing QR code has expired. Generate a new one from the Mac.")
        }

        return .success(payload)
    }

    if looksLikeRemodexPairingPayload(data) {
        return .bridgeUpdateRequired(
            makeScannerBridgeUpdatePrompt(
                message: "This QR code looks like it came from an older bridge version. Update and try again."
            )
        )
    }

    return .scanError("Not a valid pairing code. Scan the QR from xatlas Settings → Remote Access.")
}

private func looksLikeRemodexPairingPayload(_ data: Data) -> Bool {
    guard let jsonObject = try? JSONSerialization.jsonObject(with: data),
          let object = jsonObject as? [String: Any] else {
        return false
    }

    let pairingKeys: Set<String> = [
        "relay", "sessionId", "macDeviceId", "macIdentityPublicKey", "expiresAt", "v",
    ]
    return !pairingKeys.isDisjoint(with: object.keys)
}

private func makeScannerBridgeUpdatePrompt(message: String) -> CodexBridgeUpdatePrompt {
    CodexBridgeUpdatePrompt(
        title: "Update Required",
        message: message,
        command: qrScannerBridgeUpdateCommand
    )
}
